[tool.poetry]
name = "remarkable-upload"
version = "0.1.0"
description = ""
authors = ["Luca Peric <lucapericlp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.0"
tqdm = "^4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
